version: "3.7"
services:
  postgres:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
    env_file: ./.env.local #Here we are using the already existing .env.local file
volumes:
  data:
